### ISSUE TITLE
Investigate why the menu nav is not centred

### ISSUE THREAD

**Issue by CorinnaPhillips** [OliviaGreenwell/oliviagreenwell.github.io#11]
For some reason, the menu bar options are not centred on the page - is it possible to investigate why?

<img width="973" alt="menu not centred" src="https://cloud.githubusercontent.com/assets/16986048/24357070/50346c9c-12f4-11e7-8565-73ff7fbd44dc.png">

**Comment by DavidForster** [comment]
Pages without a sort order are still appearing in navigation, but without a navigation title. These are pushing the correct items to the right.

**Comment by DavidForster** [comment]
Fixed by commit fc59359
