### ISSUE TITLE
Contact form doesn't work

### ISSUE THREAD

**Issue by DavidForster** [OliviaGreenwell/oliviagreenwell.github.io#2]
The contact form needs wiring up to some form > email service

**Comment by DavidForster** [comment]
Suggest using formspree.io

**Comment by CorinnaPhillips** [comment]
Please can we also remove the website field from the form

**Comment by DavidForster** [comment]
Pull Request #7 created to fix this issue

**Comment by CorinnaPhillips** [comment]
Tested the form and it's working
