### ISSUE TITLE
Create ability to add a footer - for copyright, disclaimer and privacy links

### ISSUE THREAD

**Issue by CorinnaPhillips** [OliviaGreenwell/oliviagreenwell.github.io#4]
The footer will contain:
Copyright information
Brief disclaimer (couple of sentences)
Link to full site disclaimer
Link to privacy policy
Possibly link to cookie policy (unless the cookie plugin covers this - see separate ticket)

**Comment by DavidForster** [comment]
Pull request #10 created

**Comment by CorinnaPhillips** [comment]
Pull request #10 approved, and footer content added, then merged.
