### ISSUE TITLE
Set-up the domain oliviagreenwell.com for the jekyll/github site

### ISSUE THREAD

**Issue by CorinnaPhillips** [OliviaGreenwell/oliviagreenwell.github.io#8]
I have purchased oliviagreenwell.com from Go Daddy. Can the URL now be used instead of the GitHub one please?

I've attached a screen grab of some of the details I found in Go Daddy when I bought the site, but if further information is needed just let me know what.

![olivia greenwell domain details](https://cloud.githubusercontent.com/assets/16986048/22002348/4db7eb66-dc43-11e6-84ba-c8f465c31ddf.jpg)

**Comment by DavidForster** [comment]
Domain A records configured and CNAME file added to Repo
